# Generated by Django 5.1.5 on 2025-08-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_account_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="account_name",
            field=models.CharField(
                default="名無し", max_length=50, verbose_name="アカウント名"
            ),
        ),
    ]
