# Generated by Django 5.1.5 on 2025-08-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playground",
            name="baby_food_friendly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playground",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="playground",
            name="diaper_changing_station_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playground",
            name="kids_space_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playground",
            name="notes_for_infants",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="nursing_room_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playground",
            name="opening_hours",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="playground",
            name="reservation_required_for_infants",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playground",
            name="stroller_accessible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playground",
            name="website",
            field=models.URLField(default=""),
        ),
    ]
