# Generated by Django 5.1.5 on 2025-02-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_playground_description_playground_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
