# Generated by Django 5.1.5 on 2025-08-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_playground_baby_food_friendly_playground_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playground",
            name="fee",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="google_map_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="indoor_play_area",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playground",
            name="kids_toilet_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playground",
            name="parking_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playground",
            name="target_age",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
