# Generated by Django 5.1.5 on 2025-08-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_playground_fee_playground_google_map_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playground",
            name="baby_food_friendly",
        ),
        migrations.RemoveField(
            model_name="playground",
            name="reservation_required_for_infants",
        ),
        migrations.AddField(
            model_name="playground",
            name="lunch_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
