# Generated by Django 5.1.5 on 2025-08-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_playground_baby_food_friendly_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playground",
            name="notes_for_infants",
        ),
    ]
