# Generated by Django 5.1.5 on 2025-07-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playground",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
