# Generated by Django 5.1.5 on 2025-08-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_remove_playground_notes_for_infants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playground",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
