# Generated by Django 5.1.5 on 2025-07-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_playground_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="playground",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
