# Generated by Django 5.1.5 on 2025-08-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_playground_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="playground",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="fee_decimal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="playground",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="parking_info",
            field=models.CharField(
                blank=True,
                choices=[("NO", "なし"), ("FREE", "無料"), ("PAID", "有料")],
                default="NO",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="playground",
            name="target_age_end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playground",
            name="target_age_start",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
