# Generated by Django 5.1.5 on 2025-08-16 07:34

from django.db import migrations
import re
import datetime


def parse_time(time_str):
    """
    'HH:MM' or 'HH時MM分' or 'H時' format string to datetime.time object.
    """
    if not time_str:
        return None
    time_str = time_str.strip()

    # HH:MM format
    match = re.match(r"(\d{1,2}):(\d{2})", time_str)
    if match:
        hour, minute = map(int, match.groups())
        if 0 <= hour <= 23 and 0 <= minute <= 59:
            return datetime.time(hour, minute)

    # HH時MM分 or HH時 format
    match = re.match(r"(\d{1,2})時(?:(\d{2})分)?", time_str)
    if match:
        hour, minute_str = match.groups()
        hour = int(hour)
        minute = int(minute_str) if minute_str else 0
        if 0 <= hour <= 23 and 0 <= minute <= 59:
            return datetime.time(hour, minute)

    return None


def migrate_data(apps, schema_editor):
    Playground = apps.get_model("myapp", "Playground")
    for playground in Playground.objects.all():
        # opening_hours to opening_time, closing_time
        if playground.opening_hours:
            parts = re.split(r"[-〜~]", playground.opening_hours)
            if len(parts) == 2:
                playground.opening_time = parse_time(parts[0])
                playground.closing_time = parse_time(parts[1])
            elif len(parts) == 1:
                playground.opening_time = parse_time(parts[0])

        # target_age to target_age_start, target_age_end
        if playground.target_age:
            numbers = re.findall(r"\d+", playground.target_age)
            if len(numbers) == 1:
                playground.target_age_start = int(numbers[0])
            elif len(numbers) >= 2:
                playground.target_age_start = int(numbers[0])
                playground.target_age_end = int(numbers[1])

        # fee to fee_decimal
        if playground.fee:
            # "無料" は 0 とする
            if "無料" in playground.fee:
                playground.fee_decimal = 0
            else:
                numbers = re.findall(r"\d+", playground.fee.replace(",", ""))
                if numbers:
                    playground.fee_decimal = int(numbers[0])

        # parking_available to parking_info
        if playground.parking_available:
            # 既存のデータでは有料・無料の区別がないため、一旦 'FREE' に倒す
            playground.parking_info = "FREE"
        else:
            playground.parking_info = "NO"

        playground.save()


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_playground_closing_time_playground_fee_decimal_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
