# Generated by Django 5.1.5 on 2025-08-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playground",
            name="fee",
        ),
        migrations.RemoveField(
            model_name="playground",
            name="opening_hours",
        ),
        migrations.RemoveField(
            model_name="playground",
            name="parking_available",
        ),
        migrations.RemoveField(
            model_name="playground",
            name="target_age",
        ),
    ]
