# Generated by Django 5.1.5 on 2025-08-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_remove_playground_fee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playground",
            name="kids_space_available",
        ),
    ]
